//! Independent references are generated by tests/reference/generate_chromatography.py.
use chromascope::{
    chromatography::*,
    domain::{Operation, OperationId, Request},
    engine::{self, Output},
    jobs::JobControl,
};
use std::{
    io::Write,
    path::Path,
    process::{Command, Stdio},
};
fn config() -> Config {
    Config {
        smoothing: None,
        baseline: Baseline::None,
        minimum_snr: 0.0,
        boundary_fraction: 0.001,
        ..Config::default()
    }
}
fn trace(f: impl Fn(f64) -> f64) -> Trace {
    Trace::from_points(
        "synthetic".into(),
        &(0..=1600)
            .map(|i| {
                let x = i as f64 * 0.005;
                [x, f(x)]
            })
            .collect::<Vec<_>>(),
    )
}
fn gaussian(x: f64, mu: f64, sigma: f64, height: f64) -> f64 {
    height * (-0.5 * ((x - mu) / sigma).powi(2)).exp()
}
fn close(a: f64, b: f64, abs: f64, rel: f64) {
    assert!((a - b).abs() <= abs.max(rel * b.abs()), "{a} vs {b}");
}
fn manual(a: &Analysis, bounds: Vec<[f64; 2]>) -> Analysis {
    revise(
        a,
        a.revisions.len(),
        Correction::Manual {
            intervals: bounds,
            reason: "Independent comparison".into(),
        },
        "scientist",
        false,
    )
    .unwrap()
}
#[test]
fn gaussian_apex_fwhm_and_analytical_area() {
    let a = process(trace(|x| gaussian(x, 3.0, 0.3, 100.0)), config()).unwrap();
    assert_eq!(a.automatic.len(), 1);
    let p = &a.automatic[0];
    close(p.apex_minutes, 3.0, 1e-12, 0.0);
    close(
        p.fwhm_minutes.unwrap(),
        2.0 * (2.0_f64.ln() * 2.0).sqrt() * 0.3,
        3e-5,
        0.0,
    );
    let m = manual(&a, vec![[0.0, 8.0]]);
    close(
        m.peaks()[0].area_intensity_minutes,
        100.0 * 0.3 * (2.0 * std::f64::consts::PI).sqrt(),
        1e-8,
        1e-8,
    );
    assert_eq!(a.raw, m.raw);
    assert_eq!(a.segments, m.segments);
}
#[test]
fn asymmetric_peak_area_against_exact_gamma_integral() {
    // Causal gamma-shape x^2 exp(-x/tau). Integral = 2 tau^3; mode = 2 tau.
    let tau = 0.25;
    let a = process(
        trace(|x| {
            let u = (x - 1.0).max(0.0);
            200.0 * u * u * (-u / tau).exp()
        }),
        config(),
    )
    .unwrap();
    close(a.automatic[0].apex_minutes, 1.0 + 2.0 * tau, 1e-12, 0.0);
    let m = manual(&a, vec![[0.0, 8.0]]);
    close(
        m.peaks()[0].area_intensity_minutes,
        200.0 * 2.0 * tau.powi(3),
        1e-6,
        1e-6,
    );
}
#[test]
fn overlaps_partition_without_double_counting_and_unresolved_is_flagged_by_scope() {
    let a = process(
        trace(|x| gaussian(x, 3.0, 0.3, 100.0) + gaussian(x, 3.8, 0.3, 90.0)),
        config(),
    )
    .unwrap();
    assert_eq!(a.automatic.len(), 2);
    assert_eq!(a.automatic[0].end_minutes, a.automatic[1].start_minutes);
    assert!(a
        .automatic
        .iter()
        .all(|p| p.flags.contains(&"valley_split_overlap".into())));
    let bounds = [a.automatic[0].start_minutes, a.automatic[1].end_minutes];
    let m = manual(&a, vec![bounds]);
    close(
        a.automatic.iter().map(|p| p.area_intensity_minutes).sum(),
        m.peaks()[0].area_intensity_minutes,
        1e-10,
        1e-10,
    );
    assert!(revise(
        &a,
        0,
        Correction::Manual {
            intervals: vec![[2., 4.], [3., 5.]],
            reason: "overlap".into()
        },
        "test",
        false
    )
    .is_err());
    let unresolved = process(
        trace(|x| gaussian(x, 3.0, 0.3, 100.0) + gaussian(x, 3.1, 0.3, 90.0)),
        config(),
    )
    .unwrap();
    assert_eq!(unresolved.automatic.len(), 1);
}
#[derive(serde::Deserialize)]
struct Reference {
    x: Vec<f64>,
    raw: Vec<f64>,
    smoothed: Vec<f64>,
    baseline: Vec<f64>,
    interval: [f64; 2],
    area: f64,
    apex: f64,
    irregular: Vec<f64>,
    irregular_raw: Vec<f64>,
    irregular_smoothed: Vec<f64>,
}
#[test]
fn scipy_smoothing_baseline_apex_and_trapezoid_references() {
    let r: Reference = serde_json::from_str(include_str!("reference/chromatography.json")).unwrap();
    let points: Vec<_> = r.x.iter().zip(&r.raw).map(|(x, y)| [*x, *y]).collect();
    let a = process(
        Trace::from_points("SciPy".into(), &points),
        Config {
            minimum_snr: 5.0,
            ..Config::default()
        },
    )
    .unwrap();
    let s = &a.segments[0];
    for (a, b) in s.smoothed.iter().zip(&r.smoothed) {
        close(*a, *b, 1e-10, 1e-10);
    }
    for (a, b) in s.baseline.iter().zip(&r.baseline) {
        close(*a, *b, 1e-7, 1e-7);
    }
    assert_eq!(a.automatic.len(), 1);
    close(a.automatic[0].apex_minutes, r.apex, 1e-12, 0.0);
    let m = manual(&a, vec![r.interval]);
    close(m.peaks()[0].area_intensity_minutes, r.area, 1e-7, 1e-7);
    let points: Vec<_> = r
        .irregular
        .iter()
        .zip(&r.irregular_raw)
        .map(|(x, y)| [*x, *y])
        .collect();
    let b = process(
        Trace::from_points("irregular".into(), &points),
        Config {
            baseline: Baseline::None,
            minimum_snr: 0.0,
            ..Config::default()
        },
    )
    .unwrap();
    for (a, b) in b.segments[0].smoothed.iter().zip(r.irregular_smoothed) {
        close(*a, b, 1e-10, 1e-10);
    }
}
#[test]
fn polynomial_edges_irregular_sampling_and_signed_negative_areas() {
    let x = [0.0, 0.03, 0.2, 0.21, 0.5, 0.8, 1.0, 1.1, 1.8, 2.0];
    let points: Vec<_> = x.iter().map(|&x| [x, -3.0 + 2.0 * x - x * x]).collect();
    let a = process(
        Trace::from_points("quadratic".into(), &points),
        Config {
            smoothing: Some(SavitzkyGolay {
                window: 5,
                degree: 2,
            }),
            ..config()
        },
    )
    .unwrap();
    for (a, b) in a.segments[0].raw.iter().zip(&a.segments[0].smoothed) {
        close(*a, *b, 1e-11, 0.0);
    }
    assert!(a.automatic.is_empty());
    let m = manual(&a, vec![[0.0, 2.0]]);
    assert!(m.peaks()[0].area_intensity_minutes < 0.0);
    assert_eq!(m.raw.samples[0].intensity, Some(-3.0));
    assert!(a.warnings.iter().any(|w| w.contains("Negative")));
}
#[test]
fn noise_estimator_linear_drift_and_width_constraints() {
    // Deterministic Box-Muller white Gaussian noise, generated independently of
    // the robust estimator; 20k observations allow a 4% sigma tolerance.
    let mut seed = 42u64;
    let mut uniform = || {
        seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1);
        ((seed >> 11) as f64 + 0.5) / (1u64 << 53) as f64
    };
    let x: Vec<_> = (0..20000).map(|i| i as f64 * 0.001).collect();
    let y: Vec<_> = x
        .iter()
        .map(|x| {
            let u = uniform();
            let v = uniform();
            5.0 + 2.0 * x + 3.0 * (-2.0 * u.ln()).sqrt() * (2.0 * std::f64::consts::PI * v).cos()
        })
        .collect();
    close(noise_sigma(&x, &y), 3.0, 0.12, 0.0);
    let raw = trace(|x| gaussian(x, 3.0, 0.3, 100.0));
    assert!(process(
        raw.clone(),
        Config {
            minimum_width_minutes: 1.0,
            ..config()
        }
    )
    .unwrap()
    .automatic
    .is_empty());
    assert!(process(
        raw,
        Config {
            maximum_width_minutes: 0.2,
            ..config()
        }
    )
    .unwrap()
    .automatic
    .is_empty());
}
#[test]
fn baseline_drift_chord_and_rolling_quantile() {
    let a = process(
        trace(|x| 10.0 + 2.0 * x + gaussian(x, 3.0, 0.3, 100.0)),
        Config {
            baseline: Baseline::EndpointChord,
            ..config()
        },
    )
    .unwrap();
    for (x, b) in a.segments[0].rt_minutes.iter().zip(&a.segments[0].baseline) {
        close(*b, 10.0 + 2.0 * x, 1e-10, 0.0);
    }
    close(
        manual(&a, vec![[0.0, 8.0]]).peaks()[0].area_intensity_minutes,
        100.0 * 0.3 * (2.0 * std::f64::consts::PI).sqrt(),
        1e-8,
        1e-8,
    );
    let b = process(
        trace(|x| 10.0 + gaussian(x, 3.0, 0.1, 100.0)),
        Config {
            baseline: Baseline::RollingQuantile {
                window: 401,
                quantile: 0.1,
            },
            ..config()
        },
    )
    .unwrap();
    close(b.segments[0].baseline[600], 10.0, 1e-8, 0.0);
}
#[test]
fn missing_points_gaps_empty_and_invalid_parameters() {
    let mut raw = trace(|x| gaussian(x, 3.0, 0.3, 100.0));
    raw.samples[600].intensity = None;
    let a = process(raw, config()).unwrap();
    assert_eq!(a.segments.len(), 2);
    assert!(revise(
        &a,
        0,
        Correction::Manual {
            intervals: vec![[2.0, 4.0]],
            reason: "missing".into()
        },
        "test",
        false
    )
    .is_err());
    let empty = process(
        Trace {
            name: "empty".into(),
            samples: vec![],
        },
        config(),
    )
    .unwrap();
    assert!(empty.segments.is_empty());
    assert!(empty.automatic.is_empty());
    let mut gap = trace(|_| 0.0);
    gap.samples.retain(|p| p.rt < 3.0 || p.rt > 4.0);
    assert_eq!(
        process(
            gap,
            Config {
                maximum_gap_minutes: Some(0.1),
                ..config()
            }
        )
        .unwrap()
        .segments
        .len(),
        2
    );
    let raw = trace(|_| 0.0);
    for bad in [
        Config {
            smoothing: Some(SavitzkyGolay {
                window: 4,
                degree: 2,
            }),
            ..config()
        },
        Config {
            baseline: Baseline::AsymmetricLeastSquares {
                lambda: -1.0,
                asymmetry: 0.1,
                iterations: 10,
            },
            ..config()
        },
        Config {
            minimum_snr: f64::NAN,
            ..config()
        },
    ] {
        assert!(process(raw.clone(), bad).is_err());
    }
    let mut bad = raw.clone();
    bad.samples[1].rt = bad.samples[0].rt;
    assert!(process(bad, config()).is_err());
    let mut bad = raw;
    bad.samples[2].intensity = Some(f64::INFINITY);
    assert!(process(bad, config()).is_err());
}
#[test]
fn preview_manual_reference_accept_undo_and_corruption() {
    let a = process(trace(|x| gaussian(x, 3.0, 0.3, 100.0)), config()).unwrap();
    let original = a.clone();
    let correction = Correction::Reference {
        intervals: vec![[1.5, 3.5]],
        shift_minutes: 0.5,
        reason: "RT shift from standard".into(),
    };
    let proposal = revise(&a, 0, correction.clone(), "reviewer", true).unwrap();
    assert_eq!(a, original);
    assert!(proposal.warnings.iter().any(|w| w.contains("preview")));
    let b = revise(&a, 0, correction, "reviewer", false).unwrap();
    assert_eq!(b.peaks()[0].start_minutes, 2.0);
    assert_eq!(b.automatic, a.automatic);
    let accepted = revise(
        &b,
        1,
        Correction::Accept {
            reason: "verified standard".into(),
        },
        "reviewer",
        false,
    )
    .unwrap();
    assert!(accepted.revisions[1].reviewed);
    let restored = revise(
        &accepted,
        2,
        Correction::Restore {
            revision: 0,
            reason: "undo".into(),
        },
        "reviewer",
        false,
    )
    .unwrap();
    assert_eq!(restored.peaks(), a.peaks());
    assert_eq!(restored.revisions.len(), 3);
    verify(&restored).unwrap();
    assert_eq!(
        revise(
            &restored,
            0,
            Correction::Accept {
                reason: "stale".into()
            },
            "r",
            false
        )
        .unwrap_err()
        .code,
        "stale_revision"
    );
    let mut corrupt = restored;
    corrupt.segments[0].raw[0] += 1.0;
    assert_eq!(verify(&corrupt).unwrap_err().code, "corrupt_result");
}
fn request(operation: Operation) -> Request {
    Request {
        version: 1,
        operation_id: OperationId::default(),
        actor: "reference-test".into(),
        operation,
    }
}
#[test]
fn engine_cli_batch_roundtrip_and_no_overwrite_csv() {
    let raw = trace(|x| gaussian(x, 3.0, 0.3, 100.0));
    let req = request(Operation::ProcessChromatograms {
        traces: vec![raw.clone(), raw],
        config: config(),
    });
    let expected = engine::execute(Path::new("-"), req.clone(), &JobControl::default()).unwrap();
    let mut child = Command::new(env!("CARGO_BIN_EXE_chromascope-cli"))
        .args(["run", "-"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .unwrap();
    child
        .stdin
        .take()
        .unwrap()
        .write_all(&serde_json::to_vec(&req).unwrap())
        .unwrap();
    let output = child.wait_with_output().unwrap();
    assert!(output.status.success());
    let value: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    let actual: engine::Response = serde_json::from_value(value["result"].clone()).unwrap();
    let Output::ChromatographicProcessing { analyses: a, .. } = actual.output else {
        panic!()
    };
    let Output::ChromatographicProcessing { analyses: b, .. } = expected.output else {
        panic!()
    };
    assert_eq!(a, b);
    let table = engine::execute(
        Path::new("-"),
        request(Operation::ExportChromatographicPeaks {
            analyses: a.clone(),
        }),
        &JobControl::default(),
    )
    .unwrap();
    let Output::ChromatographicPeakTable { csv, .. } = table.output else {
        panic!()
    };
    assert_eq!(csv, peaks_csv(&a));
    let dir = tempfile::tempdir().unwrap();
    let target = dir.path().join("peaks.csv");
    for should_succeed in [true, false] {
        let mut c = Command::new(env!("CARGO_BIN_EXE_chromascope-cli"))
            .arg("export-peaks")
            .arg(&target)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .unwrap();
        c.stdin.take().unwrap().write_all(&output.stdout).unwrap();
        assert_eq!(
            c.wait_with_output().unwrap().status.success(),
            should_succeed
        );
    }
    let csv = std::fs::read_to_string(target).unwrap();
    assert!(csv.contains("area_intensity_min"));
    assert_eq!(csv.lines().count(), 3);
}
#[test]
fn truncated_width_is_missing_and_between_scan_area_is_exact() {
    let a = process(
        Trace::from_points("triangle".into(), &[[0.0, 0.0], [1.0, 10.0], [2.0, 0.0]]),
        config(),
    )
    .unwrap();
    let m = manual(&a, vec![[0.75, 1.25]]);
    assert_eq!(m.peaks()[0].fwhm_minutes, None);
    assert!(m.peaks()[0].flags.contains(&"truncated_half_height".into()));
    close(m.peaks()[0].area_intensity_minutes, 4.375, 1e-12, 0.0);
    assert_eq!(m.peaks()[0].apex_minutes, 1.0);
    assert!(peaks_csv(&[m]).contains("4.375"));
    let big = process(
        Trace::from_points(
            "overflow".into(),
            &[[0.0, 1e308], [1.0, 1e308], [2.0, 1e308]],
        ),
        config(),
    );
    assert!(
        big.is_err()
            || revise(
                &big.unwrap(),
                0,
                Correction::Manual {
                    intervals: vec![[0.0, 2.0]],
                    reason: "overflow".into()
                },
                "test",
                false
            )
            .is_err()
    );
}
#[test]
fn cli_project_preview_never_changes_project_even_on_failure() {
    use chromascope::project::Project;
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().join("project");
    let project = Project::create(&root).unwrap();
    let a = process(trace(|x| gaussian(x, 3.0, 0.3, 100.0)), config()).unwrap();
    let dataset = Path::new(env!("CARGO_MANIFEST_DIR")).join("test_file/data_dependent_02.mzML");
    for expected_revision in [0, 1] {
        let req = request(Operation::ReviseChromatogram {
            analysis: Box::new(a.clone()),
            expected_revision,
            correction: Correction::Manual {
                intervals: vec![[2.0, 4.0]],
                reason: "Project preview".into(),
            },
            preview: true,
        });
        let mut child = Command::new(env!("CARGO_BIN_EXE_chromascope-cli"))
            .arg("run")
            .arg(&dataset)
            .arg(&root)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .unwrap();
        child
            .stdin
            .take()
            .unwrap()
            .write_all(&serde_json::to_vec(&req).unwrap())
            .unwrap();
        let out = child.wait_with_output().unwrap();
        assert_eq!(out.status.success(), expected_revision == 0);
        let unchanged = Project::open(&root).unwrap();
        assert_eq!(unchanged.revision, project.revision);
        assert!(unchanged.sources.is_empty());
        assert!(unchanged.results.is_empty());
    }
    let mut p = Project::open(&root).unwrap();
    let id = p.register(&dataset).unwrap();
    let response = engine::execute(
        &dataset,
        request(Operation::ReviseChromatogram {
            analysis: Box::new(a),
            expected_revision: 0,
            correction: Correction::Manual {
                intervals: vec![[2.0, 4.0]],
                reason: "Attempted preview commit".into(),
            },
            preview: true,
        }),
        &JobControl::default(),
    )
    .unwrap();
    assert!(p.add_result(&root, id, &response).is_err());
    assert!(p.results.is_empty());
}
