name: Deploy Rust Docs to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Generate Docs
      shell: bash
      run: |
        cargo doc --no-deps
        rm -rf ./docs
        mkdir -p docs
        cp -r target/doc/* docs/
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs